Warning: Permanently added '35.197.40.107' (ECDSA) to the list of known hosts.
W0619 20:58:49.153472 140268771174144 tf_logging.py:126] Estimator's model_fn (<function resnet_model_fn at 0x7f9271de4320>) includes params argument, but params are not passed to Estimator.
I0619 20:58:49.153987 140268771174144 tf_logging.py:116] Using config: {'_save_checkpoints_secs': None, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f9271ddd590>, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=8, computation_shape=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None), '_tf_random_seed': None, '_cluster': <tensorflow.contrib.cluster_resolver.python.training.tpu_cluster_resolver.TPUClusterResolver object at 0x7f9271ddd4d0>, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_global_id_in_cluster': 0, '_session_config': allow_soft_placement: true
cluster_def {
}
, '_train_distribute': None, '_is_chief': True, '_save_checkpoints_steps': 600, '_save_summary_steps': 100, '_model_dir': '/tmp', '_master': ''}
I0619 20:58:49.154220 140268771174144 tf_logging.py:116] Precision: float32
I0619 20:58:49.154480 140268771174144 tf_logging.py:116] Training for 2000 steps (0.10 epochs in total). Current step 0.
I0619 20:58:49.313838 140268771174144 tf_logging.py:116] Calling model_fn.
I0619 20:58:49.314007 140268771174144 tf_logging.py:116] Running train on CPU
I0619 20:58:53.021321 140268771174144 tf_logging.py:116] Done calling model_fn.
I0619 20:58:53.022434 140268771174144 tf_logging.py:116] Create CheckpointSaverHook.
I0619 20:58:55.204659 140268771174144 tf_logging.py:116] Graph was finalized.
2018-06-19 20:58:55.205017: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-19 20:58:55.332820: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-06-19 20:58:55.333219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:00:04.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2018-06-19 20:58:55.333238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-19 20:58:55.660307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-19 20:58:55.660354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-19 20:58:55.660363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-19 20:58:55.660706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15127 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
I0619 20:58:57.338009 140268771174144 tf_logging.py:116] Running local_init_op.
I0619 20:58:57.402705 140268771174144 tf_logging.py:116] Done running local_init_op.
I0619 20:59:23.639081 140268771174144 tf_logging.py:116] Saving checkpoints for 1 into /tmp/model.ckpt.
I0619 20:59:24.690582 140268771174144 tf_logging.py:116] loss = 7.98753, step = 0
I0619 21:00:04.283639 140268771174144 tf_logging.py:116] global_step/sec: 2.52565
I0619 21:00:04.284684 140268771174144 tf_logging.py:116] loss = 7.9780626, step = 100 (39.594 sec)
I0619 21:00:40.564552 140268771174144 tf_logging.py:116] global_step/sec: 2.75627
I0619 21:00:40.565629 140268771174144 tf_logging.py:116] loss = 7.9498286, step = 200 (36.281 sec)
I0619 21:01:17.282639 140268771174144 tf_logging.py:116] global_step/sec: 2.72345
I0619 21:01:17.283979 140268771174144 tf_logging.py:116] loss = 7.9504285, step = 300 (36.718 sec)
I0619 21:01:53.719242 140268771174144 tf_logging.py:116] global_step/sec: 2.74449
I0619 21:01:53.720335 140268771174144 tf_logging.py:116] loss = 7.9720306, step = 400 (36.436 sec)
I0619 21:02:30.938608 140268771174144 tf_logging.py:116] global_step/sec: 2.68677
I0619 21:02:30.939699 140268771174144 tf_logging.py:116] loss = 7.9649105, step = 500 (37.219 sec)
I0619 21:03:07.200994 140268771174144 tf_logging.py:116] Saving checkpoints for 601 into /tmp/model.ckpt.
I0619 21:03:07.926727 140268771174144 tf_logging.py:116] global_step/sec: 2.70357
I0619 21:03:07.927881 140268771174144 tf_logging.py:116] loss = 7.950462, step = 600 (36.988 sec)
I0619 21:03:45.018336 140268771174144 tf_logging.py:116] global_step/sec: 2.69603
I0619 21:03:45.019475 140268771174144 tf_logging.py:116] loss = 7.945739, step = 700 (37.092 sec)
I0619 21:04:21.262236 140268771174144 tf_logging.py:116] global_step/sec: 2.75908
I0619 21:04:21.263413 140268771174144 tf_logging.py:116] loss = 7.933141, step = 800 (36.244 sec)
I0619 21:04:57.705790 140268771174144 tf_logging.py:116] global_step/sec: 2.74397
I0619 21:04:57.706954 140268771174144 tf_logging.py:116] loss = 7.923709, step = 900 (36.444 sec)
I0619 21:05:34.483145 140268771174144 tf_logging.py:116] global_step/sec: 2.71906
I0619 21:05:34.484249 140268771174144 tf_logging.py:116] loss = 7.9260426, step = 1000 (36.777 sec)
I0619 21:06:11.748975 140268771174144 tf_logging.py:116] global_step/sec: 2.68342
I0619 21:06:11.750355 140268771174144 tf_logging.py:116] loss = 7.926985, step = 1100 (37.266 sec)
I0619 21:06:49.405702 140268771174144 tf_logging.py:116] Saving checkpoints for 1201 into /tmp/model.ckpt.
I0619 21:06:50.144992 140268771174144 tf_logging.py:116] global_step/sec: 2.60443
I0619 21:06:50.146203 140268771174144 tf_logging.py:116] loss = 7.9043183, step = 1200 (38.396 sec)
I0619 21:07:28.624011 140268771174144 tf_logging.py:116] global_step/sec: 2.59882
I0619 21:07:28.625160 140268771174144 tf_logging.py:116] loss = 7.9452353, step = 1300 (38.479 sec)
I0619 21:08:05.315675 140268771174144 tf_logging.py:116] global_step/sec: 2.72541
I0619 21:08:05.316736 140268771174144 tf_logging.py:116] loss = 7.9169993, step = 1400 (36.692 sec)
I0619 21:08:41.921013 140268771174144 tf_logging.py:116] global_step/sec: 2.73184
I0619 21:08:41.922239 140268771174144 tf_logging.py:116] loss = 7.948446, step = 1500 (36.605 sec)
I0619 21:09:18.646248 140268771174144 tf_logging.py:116] global_step/sec: 2.72292
I0619 21:09:18.647404 140268771174144 tf_logging.py:116] loss = 7.9419146, step = 1600 (36.725 sec)
I0619 21:09:55.703375 140268771174144 tf_logging.py:116] global_step/sec: 2.69854
I0619 21:09:55.704478 140268771174144 tf_logging.py:116] loss = 7.9240727, step = 1700 (37.057 sec)
I0619 21:10:32.495759 140268771174144 tf_logging.py:116] Saving checkpoints for 1801 into /tmp/model.ckpt.
I0619 21:10:33.356232 140268771174144 tf_logging.py:116] global_step/sec: 2.65584
I0619 21:10:33.357336 140268771174144 tf_logging.py:116] loss = 7.8692484, step = 1800 (37.653 sec)
I0619 21:11:09.444905 140268771174144 tf_logging.py:116] global_step/sec: 2.77096
I0619 21:11:09.446062 140268771174144 tf_logging.py:116] loss = 7.929555, step = 1900 (36.089 sec)
I0619 21:11:45.673558 140268771174144 tf_logging.py:116] Saving checkpoints for 2000 into /tmp/model.ckpt.
I0619 21:11:46.668873 140268771174144 tf_logging.py:116] Loss for final step: 7.8747644.
I0619 21:11:46.669286 140268771174144 tf_logging.py:116] Starting to evaluate.
I0619 21:11:46.752652 140268771174144 tf_logging.py:116] Calling model_fn.
I0619 21:11:46.752834 140268771174144 tf_logging.py:116] Running eval on CPU
I0619 21:11:48.361999 140268771174144 tf_logging.py:116] Done calling model_fn.
I0619 21:11:48.378077 140268771174144 tf_logging.py:116] Starting evaluation at 2018-06-19-21:11:48
I0619 21:11:48.964250 140268771174144 tf_logging.py:116] Graph was finalized.
2018-06-19 21:11:48.964578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-19 21:11:48.964618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-19 21:11:48.964635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-19 21:11:48.964642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-19 21:11:48.964764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15127 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
I0619 21:11:48.964946 140268771174144 tf_logging.py:116] Restoring parameters from /tmp/model.ckpt-2000
I0619 21:11:49.355112 140268771174144 tf_logging.py:116] Running local_init_op.
I0619 21:11:49.378856 140268771174144 tf_logging.py:116] Done running local_init_op.
I0619 21:12:11.566162 140268771174144 tf_logging.py:116] Evaluation [78/781]
I0619 21:12:25.231388 140268771174144 tf_logging.py:116] Evaluation [156/781]
I0619 21:12:38.203428 140268771174144 tf_logging.py:116] Evaluation [234/781]
I0619 21:12:51.638295 140268771174144 tf_logging.py:116] Evaluation [312/781]
I0619 21:13:04.515583 140268771174144 tf_logging.py:116] Evaluation [390/781]
I0619 21:13:17.762784 140268771174144 tf_logging.py:116] Evaluation [468/781]
I0619 21:13:31.131611 140268771174144 tf_logging.py:116] Evaluation [546/781]
I0619 21:13:44.417156 140268771174144 tf_logging.py:116] Evaluation [624/781]
I0619 21:13:57.230645 140268771174144 tf_logging.py:116] Evaluation [702/781]
I0619 21:14:09.308748 140268771174144 tf_logging.py:116] Evaluation [780/781]
I0619 21:14:09.416814 140268771174144 tf_logging.py:116] Evaluation [781/781]
I0619 21:14:09.489562 140268771174144 tf_logging.py:116] Finished evaluation at 2018-06-19-21:14:09
I0619 21:14:09.489798 140268771174144 tf_logging.py:116] Saving dict for global step 2000: global_step = 2000, loss = 7.8702474, top_1_accuracy = 0.0059419014, top_5_accuracy = 0.021947023
I0619 21:14:09.934760 140268771174144 tf_logging.py:116] Eval results: {'loss': 7.8702474, 'top_1_accuracy': 0.0059419014, 'global_step': 2000, 'top_5_accuracy': 0.021947023}
I0619 21:14:09.934983 140268771174144 tf_logging.py:116] Finished training up to step 2000. Elapsed seconds 920.
